name : "Terraform plan and deploy"

on: 
 
 pull_request:
  branches: 
    -main
    -develop

 push:
  branches:
   -main
   -develop
 
 jobs:
  terraform: 
   name: Terraform Plan
   runs-on: ubuntu-latest

   steps:

   -name: checkout code
    uses: actions/checkout@v2

  -name: setup Terraform
   uses: hashicorp/setup-terraform@v1

  -name: Terraform init
   run: terraform init

  -name: Terracorm plan
   run: terraform plan
   env:
      TF_INPUT: "false"
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
